name = "CreateAndSpace-1.20.1"
version = "3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e4a5526fdc4cfe7f2591d14d65dfca0fe6fecc67d01481150dc05ff61537995"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
