name = "CreateAndSpace-1.20.1"
version = "3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa37f6201beb1bc2a1b1c149128df579586008bbefe4e40ac1d71eeb93b40f8a"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
